version: '2'

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    domainname: localhost
    volumes:
      - ./scripts_mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ancestry
      MYSQL_USER: ancestry
      MYSQL_PASSWORD: ancestry
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    hostname: web
    domainname: localhost
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - ./php/:/var/www/html
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
